name: manual-deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to deploy'
        required: true
        default: develop

jobs:
  process_inputs:
    runs-on: ubuntu-18.04
    outputs:
      type: ${{ steps.inputs_type.outputs.type }}
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: ref
        id: inputs_type
        run: |
          if [[ ${{ github.event.inputs.ref }} =~ ^v?\d\.\d\.\d$ ]]; then
              echo ::set-output name=type::version
              echo "version"
          else
              echo ::set-output name=type::branch
              echo "branch"
          fi

  deploy_branch:
    runs-on: ubuntu-18.04
    needs: process_inputs
    if: ${{ needs.process_inputs.outputs.type == 'branch' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/${{ github.event.inputs.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12.13'

      - name: Prepare .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Configure AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          SOURCE_DIR: build
          AWS_S3_BUCKET: lmaas-clientfrontend-gideon-dev-890530445547-eu-west-1

  deploy_version:
    runs-on: ubuntu-18.04
    needs: process_inputs
    if: ${{ needs.process_inputs.outputs.type == 'version' }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12.13'

      - name: Create .npmrc
        run: |
          echo "@gideonnn:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc

      - name: Download artifact
        run: yarn add ${{ github.repository }}

      - name: Configure AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          SOURCE_DIR: build
          AWS_S3_BUCKET: lmaas-clientfrontend-gideon-dev-890530445547-eu-west-1
